# .goreleaser.yaml
version: 2
project_name: tnctl

before:
  hooks:
    - go mod tidy

builds:
  - binary: tnctl
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - maintainer: Teknoir <info@teknoir.ai>
    description: Teknoir Control CLI
    homepage: https://teknoir.ai
    license: Apache 2.0
    formats:
      - deb
      - rpm
      - apk
    contents:
      - src: ./scripts/install.sh
        dst: /usr/share/tnctl/install.sh
        packager_config:
          file_info:
            mode: 0755

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
